### ISSUE TITLE
cant send file (video)

### ISSUE THREAD

**Issue by arshiay** [aiogram/telegram-bot-api#17]
hi cant send file (video ) over 150MB is there any setting?

**Comment by JrooTJunior** [comment]
You cannot upload or send files larger than the size described in the bot API documentation over the network (HTTP requests), but you can do so using local mode and working with local files on disk.

So when you set `TELEGRAM_LOCAL=1`, you can read the file after calling the `getFile` method from disk directly at the path specified in the response.

Just read the README in the official Telegram Bot API repository: https://github.com/tdlib/telegram-bot-api?tab=readme-ov-file#usage
