### ISSUE TITLE
[Question] Optimal Configuration 

### ISSUE THREAD

**Issue by RubberArchind** [aiogram/telegram-bot-api#18]
Helo, so i make a broadcast bot, im using this telegram-bot-api to increase the performance of my bot, but sometimes i got a lot pending message that not sended, is there is something i can do to resolve this issue? my VPS spec is not the problem i guess, i have a good internet connection speed too, so i think there is something i should do in telegram-bot-api itself.

I hope someone can help me with this, 
Thanks 🥂

**Comment by RubberArchind** [comment]
![image](https://github.com/aiogram/telegram-bot-api/assets/35050952/6a646ba4-51a0-40ef-a1af-ac8e56dec93c)

Here is some screenshoot of my bot working as you can see there are more than 20 pending task, a task will send a message with gif in it, the pending is not like a few minutes its just in seconds but I think that should be able to execute 20 request in a second isn't it?

**Comment by sertraline** [comment]
I don't think this is an issue with the server, it must be something with how you set up your webhooks.

**Comment by RubberArchind** [comment]
Ok thanks for the feedback, i can confirm that the problem was indeed in my webhooks not the telegram bot api itself.
