### ISSUE TITLE
Telegram API

### ISSUE THREAD

**Issue by edbek** [aiogram/telegram-bot-api#6]
What is TELEGRAM_API_ID and TELEGRAM_API_HASH ? Where to take them? Telegram only has a token.

**Comment by F0rzend** [comment]
> What is TELEGRAM_API_ID and TELEGRAM_API_HASH ? Where to take them? Telegram only has a token.

Read readme please.

Before start, you will need to obtain api-id and api-hash as described in https://core.telegram.org/api/obtaining_api_id and specify them using the TELEGRAM_API_ID and TELEGRAM_API_HASH environment variables

**Comment by edbek** [comment]
Telegram gives only a token, there is no ID and HASH.

**Comment by F0rzend** [comment]
> Telegram gives only a token, there is no ID and HASH.

![IMG_20221006_184857.jpg](https://user-images.githubusercontent.com/50886859/194359451-9578c67d-b44e-4367-8e16-9be4f50ddb4a.jpg)

seriously?

**Comment by edbek** [comment]
it is clear that they are introduced here, but where to get them?

**Comment by F0rzend** [comment]
> it is clear that they are introduced here, but where to get them?
> 

Sign up for Telegram using any application.
Log in to your Telegram core: https://my.telegram.org.
Go to "API development tools" and fill out the form.
You will get basic addresses as well as the api_id and api_hash parameters required for user authorization.

**Comment by dnslin** [comment]
```bash
docker run -d -p 8081:8081 --name=telegram-bot-api --restart=always -v telegram-bot-api-data:/var/lib/telegram-bot-api -e TELEGRAM_API_ID=xxxxx -e TELEGRAM_API_HASH=xxxxxxxx TELEGRAM_LOCAL aiogram/telegram-bot-api:latest
```

hello, i would like to ask if the above command can unlock the api restrictions of telegram ？

**Comment by JrooTJunior** [comment]
> hello, i would like to ask if the above command can unlock the api restrictions of telegram ？

@dnslin, the only file size, connections count and https restrictions can be "unlocked" via local Bot API server, just read the Telegram Docs.

**Comment by Zensonaton** [comment]
For future researchers, this is how you are supposed to run docker image with `--local` flag:
```bash
docker run -d -p 8081:8081 --name=telegram-bot-api --restart=always -v telegram-bot-api-data:/var/lib/telegram-bot-api -e TELEGRAM_LOCAL=1 -e TELEGRAM_API_ID=*** -e TELEGRAM_API_HASH=*** aiogram/telegram-bot-api:latest
```

Also, a small note: Large files aren't stored on local server.
